# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'ios_example' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ios_example

  # Use WechatOpenSDK-XCFramework instead of WechatOpenSDK
  # See https://developers.weixin.qq.com/community/develop/doc/000c62b9b0ccf8c1d65fa90b751001?blockType=1
  pod 'WechatOpenSDK-XCFramework', '~> 2.0.4'

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
      end
    end
  end
end
