name: CI

on:
  push:
    branches:
    - '*'
    - '!gh-pages'
  pull_request:
    branches:
    - '*'
    - '!gh-pages'

jobs:
  test:
    runs-on: macos-10.15
    steps:
    - uses: actions/checkout@v2
    # install swiftformat 0.47.0
    - run: brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/ecf0ff050adb374d845c7875c9a9b0524e616abd/Formula/swiftformat.rb
    - run: sudo xcode-select -s /Applications/Xcode_11.app/Contents/Developer
    - run: make lint
    - run: make build BUILD_SDK='"iphonesimulator13.0"'
    - run: make test TEST_DESTINATION='"platform=iOS Simulator,name=iPhone 11,OS=13.0"'
